goallist_project/accounts/urls.py
from django.urls import path
from .views import (HomeView, RegisterUserView, UserLoginView, UserLogoutView, UserEditView, GoalListView, GoalDetailView, GoalRegistView, GoalEditView, GoalDeleteView,PictGenerate, download_profile_picture)


app_name = 'accounts'
urlpatterns=[
    path('home/', HomeView.as_view(), name='home'),
    path('user_regist/', RegisterUserView.as_view(), name='user_regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user_edit/<int:pk>', UserEditView.as_view(), name='user_edit'),
    path('goal_list/<int:pk>', GoalListView.as_view(), name='goal_list'),
    path('goal_detail/<int:pk>', GoalDetailView.as_view(), name='goal_detail'),
    path('goal_delete/<int:pk>', GoalDeleteView.as_view(), name='goal_delete'),
    path('goal_regist/', GoalRegistView.as_view(), name='goal_regist'),
    path('goal_edit/<int:pk>', GoalEditView.as_view(), name='goal_edit'),
    path('pict_generate/<int:pk>', PictGenerate.as_view(), name='pict_generate'),
    path('download_profile_picture/<int:pk>', download_profile_picture, name='download_profile_picture'),
    
]

goallist_project/goallist_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

goallist_project/accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core import validators
from datetime import datetime
from .models import Users, Goals, Tasks
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import AuthenticationForm

class RegistForm(forms.ModelForm):
    username = forms.CharField(label='ユーザー名', max_length=10, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '10字以内'}))
    address = forms.EmailField(label='メールアドレス', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'xxx@mail.com'}))
    password = forms.CharField(label='パスワード', max_length=30, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '30字以内'}))
    confirm_password = forms.CharField(label='パスワード再入力', max_length=30, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '30字以内'}))
    
    class Meta:
        model = Users
        fields = ['username', 'address', 'password']

        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password'] #再入力したパスワードが合っているか
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります')
    
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class UserLoginForm(AuthenticationForm):
    username = forms.EmailField(label='メールアドレス', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'xxx@mail.com'})) #ログイン時にメルアド必須のため
    password = forms.CharField(label='パスワード', max_length=30, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '30字以内'}))
    remember = forms.BooleanField(label='ログイン状態を保持する', required=False)



# ユーザー編集用画面とフォーム作る。jobとかintroductionとかを追加する
class UserEditForm(forms.ModelForm):
    username = forms.CharField(label='名前', help_text="10字以内 / 必須", max_length=10, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '10字以内'}))
    address = forms.EmailField(label='メールアドレス', help_text="必須", widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'xxx@mail.com'}))
    job = forms.CharField(label='職業', help_text="10字以内", max_length=10, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '10字以内'}))
    introduction = forms.CharField(label='自己紹介', help_text="15字以内", max_length=15, required=False,  widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'line-height: 1.5; height: 6em;', 'placeholder': '簡潔に'}))
    birthday = forms.DateField(label='誕生日', widget=forms.DateInput(attrs={'type': 'date'}), required=True)

    class Meta:
        model = Users
        fields = ['username', 'address', 'job', 'introduction', 'birthday']
        error_messages = {
            "username": {"required": "ユーザー名が入力されていません",},
            "address": {"required": "メールアドレスが入力されていません",},
            "birthday": {"required": "誕生日を入力してください",},
        }
    
    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        user.upload_at = datetime.now()
        user.save()
        return user
    
    
    
    # 夢編集用画面とフォーム作る。
class GoalRegistForm(forms.ModelForm):
    goal_title = forms.CharField(label='叶えたい夢', max_length=15, help_text="15字以内 / 必須", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '簡潔に'}), required=True)
    goal_detail = forms.CharField(label='夢の詳細', max_length=30, help_text="30字以内", widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'line-height: 1.5; height: 6em;', 'placeholder': '改行も反映されます'}), required=False)
    
    class Meta:
        model = Goals
        fields = ['goal_title', 'goal_detail']
    
    def save(self, *args, **kwargs):
        obj = super(GoalRegistForm, self).save(commit=False)
        obj.created_at = datetime.now()
        obj.upload_at = datetime.now()
        obj.save()
        return obj


class GoalEditForm(forms.ModelForm):
    goal_title = forms.CharField(label='叶えたい夢', initial=Goals.goal_title, max_length=15, help_text="15字以内 / 必須", widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)
    goal_detail = forms.CharField(label='夢の詳細', initial=Goals.goal_detail, max_length=30, help_text="30字以内", widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'line-height: 1.5; height: 6em;'}), required=False)
    
    class Meta:
        model = Goals
        fields = ['goal_title', 'goal_detail']
    
    def save(self, *args, **kwargs):
        obj = super(GoalEditForm, self).save(commit=False)
        obj.upload_at = datetime.now()
        obj.save()
        return obj

goallist_project/templates/base.html
<!DOCTYPE html>
<html lang='ja'>
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <div>
        <nav class='navbar navbar-expand-lg navbar-light bg-light justify-content-center' style="padding:1rem 0;">
            <a class='navbar-brand' style="padding:0 3rem;" href="{% url 'accounts:home' %}">ホーム</a>

            {% if user.is_authenticated %}  {#ログインしている場合#}
            <a class='navbar-brand' style="padding:0 3rem;" href="{% url 'accounts:goal_list' pk=user.id %}">夢一覧</a>
            <a class='navbar-brand' style="padding:0 3rem;" href="{% url 'accounts:goal_regist' %}">夢登録</a>
            <a class='navbar-brand' style="padding:0 3rem;" href="{% url 'accounts:user_edit' pk=user.id %}">ユーザー情報編集</a>
            <a class='navbar-brand' style="padding:0 3rem;" href="{% url 'accounts:user_logout' %}">ログアウト</a>

            {% else %}  {#ログインしていない場合#}
            <a class='navbar-brand' style="padding:0 3rem;" href="{% url 'accounts:user_login' %}">ログイン</a>
            <a class='navbar-brand' style="padding:0 3rem;" href="{% url 'accounts:user_regist' %}">ユーザー登録</a>
            {% endif %}
        </nav>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

goallist_project/templates/goal_delete.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-detail">
<div style="margin: 0 auto; max-width: 800px;">
    
    <h1 class="page-title">夢の削除</h1>
    
        <div style="max-height: 400px; overflow-y: auto; padding: 10px;">
            <table class='table table-striped table-bordered' style="text-align :center;">
                <thead>
                    <tr>
                        <th>{{ object.goal_title }}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ object.goal_detail }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

    <p style="font-size: 18px; display: flex; justify-content: center; align-items: center; margin: 20px 0px 0px 0px;">この夢を削除しますか？</p>
    <div style="display: flex; justify-content: center; align-items: center; margin: 20px 0px 0px 0px;">
        <form method='POST'>
            {% csrf_token %}
            <div class="button">
                <button type="submit" class="btn btn-danger">削除する</button>
            </div>
        </form>
    </div>
        <div class="button-home">
            <a class="btn btn-light" href="{% url 'accounts:goal_list' pk=user.id %}">リストへ戻る</a>
        </div>

</div>
</body>
{% endblock %}

goallist_project/templates/goal_detail.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-detail">
<div style="margin: 0 auto; max-width: 800px;">
    
    <h1 class="page-title">夢</h1>
    
        <div style="max-height: 400px; overflow-y: auto; padding: 10px;">
            <table class='table table-striped table-bordered' style="text-align :center;">
                <thead>
                    <tr>
                        <th>{{ goal.goal_title }}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><pre>{{ goal.goal_detail }}</pre></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="button-home">
            <a class="btn btn-light" href="{% url 'accounts:goal_list' pk=user.id %}">リストへ戻る</a>
        </div>
        
    <h1 class="page-title">画像生成</h1>
    <div style="display: flex; justify-content: center; align-items: center; margin: 40px 0px 0px 0px;">
        <a class="button-pict" href="{% url 'accounts:pict_generate' pk=goal.id %}">この夢でプロフィール画像を作成する</a><br>
    </div>

</div>
</body>
{% endblock %}

goallist_project/templates/goal_edit.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-detail">
<div style="margin: 0 auto; max-width: 800px;">

    <h1 class="page-title">夢を編集する</h1>

    <form method='POST' enctype='multipart/form-data' style="max-width:300px; margin:auto" class="needs-validation" novalidate>
    {% csrf_token %}

            <div class="form-group">
                <p class="title-label">
                    <label for="id_goal_title" class="form-label">叶えたい夢</label>
                </p>
                {{ form.goal_title }}
                {% if form.goal_title.errors %}
                    <div class="error-message">{{ form.goal_title.errors.as_text }}</div>
                {% endif %}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.goal_title.help_text }}</p>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_goal_detail" class="form-label">夢の詳細</label>
                </p>
                {{ form.goal_detail }}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.goal_detail.help_text }}</p>

        <div class="button">
            <input type='submit' class="btn btn-success" value="変更">
        </div>
    </form>
</div>
<div class="button-home">
    <a class="btn btn-light" href="{% url 'accounts:goal_list' pk=user.id %}">リストへ戻る</a>
</div>
</body>
{% endblock %}

goallist_project/templates/goal_list.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-list">
<div style="margin: 0 auto; max-width: 800px;">

    {% if messages %}
        <div class="message-top">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    
    <h1 class="page-title">夢一覧</h1>

    {% if goals %}
        <div style="max-height: 400px; overflow-y: auto; padding: 10px;">
            <table class='table table-striped table-bordered' style="text-align :center;">
                <thead>
                    <tr>
                        <th>夢</th>
                        <th>変更</th>
                        <th>削除</th>
                    </tr>
                </thead>
                <tbody>
                {% for goal in goals %}
                <tr>
                    <td><a href="{% url 'accounts:goal_detail' pk=goal.id %}">{{ goal.goal_title }}</a></td>
                    <td><a href="{% url 'accounts:goal_edit' pk=goal.id %}">変更</a></td>
                    <td><a href="{% url 'accounts:goal_delete' pk=goal.id %}">削除</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <h1 style="font-size: 28px; font-weight: bold; border-bottom: double 4px; margin: 20px; padding: 20px; display: flex; justify-content: center; align-items: center;">リストは真っ白です。叶えたい夢を登録しましょう。</h1>
        <div class="button">
            <a class="btn btn-primary" href="{% url 'accounts:goal_regist' %}">夢を登録する</a>
        </div>
    {% endif %}
</div>
</body>
{% endblock %}

goallist_project/templates/goal_regist.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-home">
<div style="margin: 0 auto; max-width: 800px;">

    <h1 class="page-title">夢登録</h1>

    <form method='POST' style="max-width:300px; margin:auto" class="needs-validation" novalidate>
        {% csrf_token %}

            <div class="form-group">
                <p class="title-label">
                    <label for="id_goal_title" class="form-label">叶えたい夢</label>
                </p>
                {{ form.goal_title }}
                {% if form.goal_title.errors %}
                    <div class="error-message">{{ form.goal_title.errors.as_text }}</div>
                {% endif %}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.goal_title.help_text }}</p>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_goal_detail" class="form-label">夢の詳細</label>
                </p>
                {{ form.goal_detail }}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.goal_detail.help_text }}</p>

        <div class="button">
            <button type="submit" class="btn btn-primary">夢登録</button>
        </div>
    </form>
</div>
</body>
{% endblock %}

goallist_project/templates/home.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-home">
<div style="margin: 0 auto; max-width: 800px;">

    {% if messages %}
        <div class="message-top">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <h1 class="page-title">夢100リストへようこそ</h1>
        {% if user.is_authenticated %}  {#ログインしている場合#}
            <p class="home">
                ようこそ {{ user.username }} さん。<br>
                現在時刻は{{ time }}です。
            </p>

        {% else %}  {#ログインしていない場合#}
            <p class="home">
                現在時刻は{{ time }}です。<br>
                登録済みの方はログインしてください。
            </p>
        {% endif %}
</div>
</body>
{% endblock %}

goallist_project/templates/pict_generate.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-pict">
<div style="margin: 0 auto; max-width: 800px;">
    
    <h1 class="page-title">プロフィール</h1>

    <div style="margin: 20px; display: flex; justify-content: center; align-items: center;">
        <img src="{% static 'kakouzumi.png' %}">
    </div>
</div>

<div class="button">
    <a id="downloadButton" href="{% static 'kakouzumi.png' %}" download="profile_image.png" class="btn btn-warning">画像をダウンロードする</a>
</div>
<div class="button-home">
    <a class="btn btn-light" href="{% url 'accounts:goal_list' pk=user.id %}">リストへ戻る</a>
</div>


</body>
{% endblock %}

goallist_project/templates/task_delete.html
{% extends 'base.html' %}
{% block content %}
<form method='POST'>
<h3>{{ object.goal_title }}</h3>
<div>このタスクを削除しますか？</div>
{% csrf_token %}
<input type='submit' value="削除">
</form>
<a href="{% url 'accounts:goal_list' %}">夢リストへ戻る</a>
{% endblock %}

goallist_project/templates/task_edit.html
{% extends 'base.html' %}
{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value="変更">
</form>
{% endblock %}

goallist_project/templates/task_regist.html
{% extends 'base.html' %}
{% block content %}
<div class="border">
    <div>{{ goal.goal_title }}</div>
    <div>{{ goal.goal_detail }}</div>
</div>

<form method='POST'>
    {% csrf_token %}
    {{ taskregistform.as_p }}
    <input type='submit' value="タスク登録">
</form>
<h2>タスクの一覧</h2>

        {% for task in tasks %}
        <div class="border">
            <div>{{ task.task_title }}</div>
            <div>{{ task.task_due }}</div>
        </div>
        {% empty %}
        <div>タスクはありません。</div>
        {% endfor %}

{% endblock %}

goallist_project/templates/user_edit.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-home">
<div style="margin: 0 auto; max-width: 800px;">

    <h1 class="page-title">ユーザー情報編集</h1>

    <form method='POST' enctype='multipart/form-data' style="max-width:300px; margin:auto" class="needs-validation" novalidate>
        {% csrf_token %}
            <div class="form-group">
                <p class="title-label">
                    <label for="id_username" class="form-label">ユーザーネーム</label>
                </p>
                {{ form.username }}
                {% if form.username.errors %}
                    <div class="error-message">{{ form.username.errors.as_text }}</div>
                {% endif %}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.username.help_text }}</p>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_address" class="form-label">メールアドレス</label>
                </p>
                {{ form.address }}
                {% if form.address.errors %}
                    <div class="error-message">{{ form.address.errors.as_text }}</div>
                {% endif %}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.address.help_text }}</p>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_job" class="form-label">職業</label>
                </p>
                {{ form.job }}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.job.help_text }}</p>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_introduction" class="form-label">自己紹介</label>
                </p>
                {{ form.introduction }}
            </div>
            <p id="passwordHelpBlock" class="form-text">{{ form.introduction.help_text }}</p>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_introduction" class="form-label">誕生日</label>
                </p>
                {{ form.birthday }}
            </div>
            <p id="passwordHelpBlock" class="form-text">デフォルト設定 : 1900/01/01</p>
            {% if form.birthday.errors %}
                <div class="error-message">{{ form.birthday.errors.as_text }}</div>
            {% endif %}

            <div class="button">
                <input type='submit' class="btn btn-success" value="設定変更"><br>
            </div>
{% comment %} 
            {% if user.picture %}
                <p style="font-size: 16px; font-weight: bold; border-left: solid 5px #7db4e6; padding: 0.25em 0.5em; margin: 20px 0px 5px -10px; background: #c2edff;">
                    <label for="id_username" class="form-label">プロフィール画像のダウンロード</label>
                </p>
                <div style="display: flex; justify-content: center; align-items: center; margin: 20px 0px 20px 0px;">
                    <a href="{% url 'accounts:download_profile_picture' pk=user.id %}" class="btn btn-warning">ダウンロードする</a>
                </div>
                <p style="display: flex; justify-content: center; align-items: center; margin: 0px 0px 40px 0px;">※ダウンロード後はブラウザバックしてください</p>
            {% endif %}
 {% endcomment %}
        <div class="button-home">
            <a class="btn btn-light" href="{% url 'accounts:home' %}">ホームへ戻る</a>
        </div>
    </form>
</div>
</body>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

goallist_project/templates/user_regist.html
{% extends 'base.html' %}
{% load static %}
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

{% block content %}
<body class="background-home">
<div style="margin: 0 auto; max-width: 800px;">
    
    <h1 class="page-title">ユーザー登録</h1>

<form method='POST' style="max-width:300px;margin:auto">
    {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors.as_text }}
                </div>
            {% endif %}

            <div class="form-group">
                <p class="title-label">
                    <label for="id_username" class="form-label">ユーザーネーム</label>
                </p>
                {{ form.username }}
                {% if form.username.errors %}
                    <div class="error-message">{{ form.username.errors.as_text }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_address" class="form-label">メールアドレス</label>
                </p>
                {{ form.address }}
                {% if form.address.errors %}
                    <div class="error-message">{{ form.address.errors.as_text }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_password" class="form-label">パスワード</label>
                </p>
                {{ form.password }}
                {% if form.password.errors %}
                    <div class="error-message">{{ form.password.errors.as_text }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <p class="title-label">
                    <label for="id_confirm_password" class="form-label">パスワード再入力</label>
                </p>
                {{ form.confirm_password }}
                {% if form.confirm_password.errors %}
                    <div class="error-message">{{ form.confirm_password.errors.as_text }}</div>
                {% endif %}
            </div>

        <div class="button">
            <input type='submit' class="btn btn-primary" value="ユーザー登録">
        </div>
</form>
</div>
</body>
{% endblock %}